// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
static FirebaseOptions get currentPlatform {
switch (defaultTargetPlatform) {
case TargetPlatform.android:
return android;
case TargetPlatform.iOS:
return ios;
default:
throw UnsupportedError(
'DefaultFirebaseOptions are not supported for this platform.',
);
}
}

// ✅ paste your Android config here
static const FirebaseOptions android = FirebaseOptions(
apiKey: 'YOUR_ANDROID_API_KEY',
appId: 'YOUR_ANDROID_APP_ID',
messagingSenderId: 'YOUR_SENDER_ID',
projectId: 'YOUR_PROJECT_ID',
storageBucket: 'YOUR_BUCKET',
);

// (optional)
static const FirebaseOptions ios = FirebaseOptions(
apiKey: 'YOUR_IOS_API_KEY',
appId: 'YOUR_IOS_APP_ID',
messagingSenderId: 'YOUR_SENDER_ID',
projectId: 'YOUR_PROJECT_ID',
storageBucket: 'YOUR_BUCKET',
iosBundleId: 'YOUR_BUNDLE_ID',
);
}


/// Android config (from FlutterFire CLI)
static const FirebaseOptions android = FirebaseOptions(
apiKey: 'AIzaSyBTtBA1E8z9GxGYZQ2b0T2JmmS8JcFZtjw',
appId: '1:1053110957892:android:3f62ad94a8ad058499c911',
messagingSenderId: '1053110957892',
projectId: 'hostelreservation-1defd',
storageBucket: 'hostelreservation-1defd.firebasestorage.app',
);

/// iOS config (from FlutterFire CLI)
static const FirebaseOptions ios = FirebaseOptions(
apiKey: 'AIzaSyAOezQy9yhjkRcG4cN6l7pY-Rhpd2YsrJQ',
appId: '1:1053110957892:ios:ba555077fb32c3bd99c911',
messagingSenderId: '1053110957892',
projectId: 'hostelreservation-1defd',
storageBucket: 'hostelreservation-1defd.firebasestorage.app',
iosBundleId: 'com.example.hostelReservation',
);
}

