// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   throw UnsupportedError(
    //     'DefaultFirebaseOptions have not been configured for web - '
    //     'you can reconfigure this by running the FlutterFire CLI again.',
    //   );
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtBA1E8z9GxGYZQ2b0T2JmmS8JcFZtjw',
    appId: '1:1053110957892:android:3f62ad94a8ad058499c911',
    messagingSenderId: '1053110957892',
    projectId: 'hostelreservation-1defd',
    storageBucket: 'hostelreservation-1defd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOezQy9yhjkRcG4cN6l7pY-Rhpd2YsrJQ',
    appId: '1:1053110957892:ios:ba555077fb32c3bd99c911',
    messagingSenderId: '1053110957892',
    projectId: 'hostelreservation-1defd',
    storageBucket: 'hostelreservation-1defd.firebasestorage.app',
    iosBundleId: 'com.example.hostelReservation',
  );
}
